# Generated by Django 5.2.15 on 2026-06-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='agent_notified_at',
            field=models.DateTimeField(blank=True, help_text='Last time the agent was SMS-notified about this conversation.', null=True),
        ),
    ]
